modules:
  - from-file: devices/laptop/laptop-files.yml
  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - laptop # installs TLP and configures your system for laptop usage
